language: java

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] && ./gradlew build asciidoc || ./gradlew build asciidoc publishGhPages'
